package com.arsyiaziz.task5;

import java.time.LocalDate;
import java.util.ArrayList;

public class DeveloperDatabase {
    private static String[] developerNames = {
            "Apple Inc.",
            "Coleco",
            "Commodore Business Machines",
            "IBM",
            "Sinclair Research",
            "Tandy Corporation",
    };

    private static String[] developerSummaries= {
            "Apple Inc. is an American multinational technology company headquartered in Cupertino, California, that designs, develops, and sells consumer electronics, computer software, and online services. It is considered one of the Big Five companies in the U.S. information technology industry, along with Amazon, Google, Microsoft, and Facebook. Its hardware products include iPhone smartphones, iPad tablet computers, Mac personal computers, iPod portable media players, Apple Watch smartwatches, Apple TV digital media players, AirPods wireless earbuds, AirPods Max headphones, and the HomePod smart speaker line. Apple's software includes the iOS, iPadOS, macOS, watchOS, and tvOS operating systems, the iTunes media player, the Safari web browser, the Shazam music identifier, and the iLife and iWork creativity and productivity suites, as well as professional applications like Final Cut Pro, Logic Pro, and Xcode. Its online services include the iTunes Store, the iOS App Store, Mac App Store, Apple Arcade, Apple Music, Apple TV+, Apple Fitness+, iMessage, and iCloud. Other services include Apple Stores, the Genius Bar, AppleCare, Apple Pay, Apple Cash, and Apple Card.",
            "Coleco Industries, Inc. was an American company founded in 1932 by Maurice Greenberg as The Connecticut Leather Company. It became a highly successful toy company in the 1980s, known for its mass-produced version of Cabbage Patch Kids dolls and its video game consoles, the Coleco Telstar dedicated consoles and ColecoVision.While the company disappeared in 1988 as a result of bankruptcy, the Coleco brand was revived in 2005, and remains active to this day.",
            "Commodore International (other names include Commodore International Limited, or just simply Commodore) was an American home computer and electronics manufacturer founded by Jack Tramiel. Commodore International (CI), along with its subsidiary Commodore Business Machines (CBM), was a significant participant in the development of the home personal computer industry in the 1970s, 1980s and early 1990s. The company developed and marketed the world's best-selling desktop computer, the Commodore 64 (1982), and released its Amiga computer line in July 1985. With quarterly sales ending 1983 of $49 million (equivalent to $108 million in 2019), Commodore was one of the world's largest personal computer manufacturers.",
            "International Business Machines Corporation (IBM) is an American multinational technology company headquartered in Armonk, New York, with operations in over 170 countries. The company began in 1911, founded in Endicott, New York, as the Computing-Tabulating-Recording Company (CTR) and was renamed \"International Business Machines\" in 1924. IBM is incorporated in New York.\n\n" +
                    "IBM produces and sells computer hardware, middleware and software, and provides hosting and consulting services in areas ranging from mainframe computers to nanotechnology. IBM is also a major research organization, holding the record for most U.S. patents generated by a business (as of 2020) for 28 consecutive years. Inventions by IBM include the automated teller machine (ATM), the floppy disk, the hard disk drive, the magnetic stripe card, the relational database, the SQL programming language, the UPC barcode, and dynamic random-access memory (DRAM). The IBM mainframe, exemplified by the System/360, was the dominant computing platform during the 1960s and 1970s.\n",
            "Sinclair Research Ltd is a British consumer electronics company founded by Clive Sinclair in Cambridge. It was originally incorporated in 1973 as Westminster Mail Order Ltd, renamed Sinclair Instrument Ltd, then Science of Cambridge Ltd, then Sinclair Computers Ltd, and finally Sinclair Research Ltd. It remained dormant until 1976, when it was activated with the intention of continuing Sinclair's commercial work from his earlier company Sinclair Radionics, and adopted the name Sinclair Research in 1981.",
            "Tandy Corporation was an American family-owned leather goods company based in Fort Worth, Texas, United States. Tandy Leather was founded in 1919 as a leather supply store and acquired a number of craft retail companies, including RadioShack in 1963. In 2000, the Tandy Corporation name was dropped and the entity became the RadioShack Corporation.",

    };
    private static String[] developerHQs = {
            "Cupertino, California, United States",
            "West Hartford, Connecticut, United States",
            "West Chester, Pennsylvania, United States",
            "Armonk, New York, United States",
            "London, England, UK",
            "Fort Worth, Texas, United States",

    };

    private static int[] developerLogos = {
            R.drawable.apple,
            R.drawable.coleco,
            R.drawable.commodore,
            R.drawable.ibm,
            R.drawable.sinclair,
            R.drawable.tandy,
    };


    static ArrayList<DeveloperModel> getDevelopers() {
        ArrayList<DeveloperModel> list = new ArrayList<>();
        for (int i = 0; i < developerNames.length; i++) {
            DeveloperModel developer = new DeveloperModel();
            developer.setName(developerNames[i]);
            developer.setLogo(developerLogos[i]);
            developer.setHQ(developerHQs[i]);
            developer.setSummary(developerSummaries[i]);
            list.add(developer);
        }
        return list;
    }
}
